export const initialState = [
  {
    id: 1,
    title: "Senior Product Designer",
    spec: "Design",
    subTitle: "Dhaka, Bangladesh",
    text: "Prosto text, bez ogromnogo smisla",
    cardType: "active",
    logo: "Slack",
    date: new Date(),
    candidates: "122+ candidates",
  },
  {
    id: 2,
    title: "Copywriter",
    spec: "Marketing",
    subTitle: "Dhaka, Bangladesh",
    text: "Prosto text, bez ogromnogo smisla",
    cardType: "active",
    logo: "twitch",
    date: "8 July",
    candidates: "201+ candidates",
  },
  {
    id: 3,
    title: "WordPress Developer",
    spec: "Developer",
    subTitle: "Dhaka, Bangladesh",
    text: "Prosto text, bez ogromnogo smisla",
    cardType: "active",
    logo: "spotify",
    date: "10 July",
    candidates: "60+ candidates",
  },
  {
    id: 4,
    title: "Developer",
    spec: "Developer",
    subTitle: "Dhaka, Bangladesh",
    text: "Prosto text, bez ogromnogo smisla",
    cardType: "completed",
    logo: "greeb",
    date: "4 July",
    candidates: "322+ candidates",
  },
  {
    id: 5,
    title: "Marketing",
    spec: "Marketing",
    subTitle: "Dhaka, Bangladesh",
    text: "Prosto text, bez Marketing Marketing",
    cardType: "unfinished",
    logo: "greeb",
    date: "3 July",
    candidates: "344+ candidates",
  },
  {
    id: 5,
    title: "Developer UX/UI",
    spec: "Developer",
    subTitle: "Dhaka, Bangladesh",
    text: "Prosto text, bez Developer Marketing",
    cardType: "unfinished",
    logo: "greeb",
    date: "4 July",
    candidates: "12+ candidates",
  },
];
