import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import LayoutApp from "@/components/LayoutApp/LayoutApp";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Project 2",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <LayoutApp>{children}</LayoutApp>
      </body>
    </html>
  );
}
